### ISSUE TITLE
Metering plugs are not detected

### ISSUE THREAD

**Issue by kekonn** [2Fake/devolo_home_control_api#83]
**Describe the bug**
I have code that loops over all known devices and prints them, but my metering plugs are not there. 

**To Reproduce**
Run this script

```python
import sys

from devolo_home_control_api.mydevolo import Mydevolo
from devolo_home_control_api.homecontrol import HomeControl
from devolo_home_control_api.devices.zwave import Zwave

gateway_id = ""

mydevolo = Mydevolo()
mydevolo.user = ""
mydevolo.password = ""

controller = HomeControl(gateway_id, mydevolo)

for dev in controller.get_all_devices():
    device = controller.devices.get(dev)
    print("Identifier: %s - Device: %s %s" % (dev, device.name, device.generic_device_class))

print("Done!")
```
Which outputs 

```
Identifier: hdm:ZWave:D9344F42/2 - Device: Devolo Connect Thermostat
Identifier: hdm:ZWave:D9344F42/3 - Device: Devolo Connect Thermostat
Identifier: hdm:ZWave:D9344F42/4 - Device: Unknown Unknown
Identifier: hdm:ZWave:D9344F42/5 - Device: Door/Window Contact None
Identifier: hdm:ZWave:D9344F42/6 - Device: Danfoss RS 014G0160 Thermostat Sensor Multilevel
Identifier: hdm:ZWave:D9344F42/7 - Device: Unknown Unknown
Identifier: hdm:ZWave:D9344F42/8 - Device: Unknown Unknown
Identifier: hdm:ZWave:D9344F42/9 - Device: Unknown Unknown
Identifier: hdm:ZWave:D9344F42/10 - Device: Humidity Sensor None
```

Obviously I left out any passwords etc, but [my plugs](https://www.amazon.de/-/nl/dp/B06VVKFPRR/ref=pd_rhf_ee_s_rp_c_2_0_2/257-7408158-4879439?_encoding=UTF8&pd_rd_i=B06VVKFPRR&pd_rd_r=ea6cc241-a18f-4872-b267-ea8d4e705fac&pd_rd_w=mCCxs&pd_rd_wg=OLBhd&pf_rd_p=b173a0cd-ffa9-4b13-94a4-3bfc0329646b&pf_rd_r=KKDT5RGB2WXJMTCYCM4V&psc=1&refRID=KKDT5RGB2WXJMTCYCM4V) aren't in the list. The Unknowns are my Philips Hue Bulbs added through the Bridge integration.

**Expected behavior**
I would expect my 2 metering plugs (that show up in the app on my phone) to show up in this list.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 20H2
- Python version: 3.9.0 x64

**Additional context**
Last time I checked, all devices were up to date.

**Comment by 2Fake** [comment]
Hi,

thanks for your report. But we think it's 'invalid'. You are calling the function get_all_devices which is already done by us during startup in your line 

```python
controller = HomeControl(gateway_id, mydevolo)
```
The "Unknown Unknown" devices are not your Philips Hue Bulbs. We only fetching the z-wave devices from the gateway, no other devices, like Philips Hue, because this API is mainly intended to be used in Home Assistant and they have an integration for Philips Hues directly, so we don't see the need to catch them here also. 
We think that the two of your devices are your metering plugs.

The Unknown Unknown which you are getting from your call are answer from a Z-Wave database which has no information about the metering plug because they saved it wrong. They saved like this: 0x0175/0x0x01/0x0x12 but correct would be 0x0175x0x0001x0x0012

If you want to know the name and device class of your devices, you can get it like that:

```python
for dev in controller.devices.values():
    print("Identifier: %s - Device: %s %s" % (dev.uid, dev.settings_property["general_device_settings"].name, dev.device_type))
```

**Comment by kekonn** [comment]
Thanks for the quick feedback! Using your code I do see them. I figured this was meant for HA and the likes, but something like HA is far too heavy for the little script I intend to make.

Thanks for the support!

**Comment by 2Fake** [comment]
Would you tell us what you do with our API?

**Comment by kekonn** [comment]
An adaptation of the rules feature. I find it not flexible enough, so I think I'll write a little script that checks all the rules I want to enforce and have it autorun every minute.
